# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=12, verbose_name='处理器')),
                ('vendor_id', models.CharField(max_length=12, verbose_name='厂商名字')),
                ('cpu_family', models.CharField(max_length=12, verbose_name='cpu核数')),
                ('model', models.CharField(max_length=12, verbose_name='cpu模式')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10, verbose_name='槽位')),
                ('pd_type', models.CharField(max_length=12, verbose_name='磁盘类型')),
                ('capacity', models.CharField(max_length=12, verbose_name='磁盘容量')),
                ('model', models.CharField(max_length=12, verbose_name='磁盘模式')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, verbose_name='主机ip')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=12, verbose_name='内存大小')),
                ('slot', models.CharField(max_length=10, verbose_name='内存槽位')),
                ('model', models.CharField(max_length=12, verbose_name='内存模式')),
                ('speed', models.CharField(max_length=12, verbose_name='内存速率')),
                ('manufacturer', models.CharField(max_length=12, verbose_name='内存生产商')),
                ('sn', models.CharField(max_length=12, verbose_name='内存序号')),
                ('memory_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='内存对应的主机')),
            ],
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.CharField(max_length=12, verbose_name='网卡是否开启')),
                ('hwaddr', models.CharField(max_length=12, verbose_name='Mac地址')),
                ('address', models.CharField(max_length=12, verbose_name='ip地址')),
                ('netmask', models.CharField(max_length=12, verbose_name='子网掩码')),
                ('broadcast', models.CharField(max_length=12, verbose_name='广播地址')),
                ('nic_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='网卡对应的主机')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='磁盘对应的主机'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='CPU对应的主机'),
        ),
    ]
