# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-16 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='变更信息')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('record_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Host', verbose_name='服务器')),
            ],
        ),
    ]
